/**
 * MiCA Template Field Definitions
 *
 * Defines all OTHR (other token) fields for the MiCA whitepaper iXBRL template.
 * Sourced from the ESMA MiCA taxonomy (2025-03-31) taxonomy-bundle.json.
 *
 * Each field maps to an XBRL element and defines its rendering position in the
 * MiCA-template numbered table format (Parts A-J + Summary + Sustainability).
 */

import type { XBRLDataType, WhitepaperPart } from '@/types/taxonomy';

/**
 * MiCA field definition for a single reportable element
 */
export interface MiCAFieldDefinition {
  /** Field number as shown in MiCA template (e.g., "A.1", "E.21", "S.8") */
  number: string;
  /** Human-readable field label */
  label: string;
  /** Full XBRL element name with namespace prefix */
  xbrlElement: string;
  /** Which MiCA part this belongs to (A-J), or 'summary' for 00-08 fields, 'S' for sustainability */
  section: WhitepaperPart | 'summary' | 'S';
  /** XBRL data type */
  dataType: XBRLDataType;
  /** Period type for context reference */
  periodType: 'instant' | 'duration';
  /** Whether this is a text block (requires escape="true") */
  isTextBlock: boolean;
  /** Whether this fact goes in ix:hidden (enumeration types) */
  isHidden: boolean;
  /** Whether this is a dimensional field (management body, persons involved) */
  isDimensional: boolean;
  /** Dimension type if dimensional */
  dimensionType?: 'offerorMgmt' | 'issuerMgmt' | 'operatorMgmt' | 'personsInvolved';
}

/**
 * All OTHR fields organized by their MiCA section number.
 * Fields are ordered by their terseLabel numbering within each section.
 */
export const OTHR_FIELD_DEFINITIONS: MiCAFieldDefinition[] = [
  // =====================================================================
  // SUMMARY FIELDS (00-10) - Cover page / summary section
  // =====================================================================
  {
    number: '00',
    label: 'Table of content',
    xbrlElement: 'mica:TableOfContentForOtherTokenWhitePaper',
    section: 'summary',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: '01',
    label: 'Date of notification of white paper',
    xbrlElement: 'mica:DateOfNotificationForOtherTokenWhitePaper',
    section: 'summary',
    dataType: 'dateItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: '02',
    label: 'Statement ensuring compliance with underlying regulation',
    xbrlElement: 'mica:StatementEnsuringComplianceWithUnderlyingRegulation',
    section: 'summary',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: '03',
    label: 'Compliance statement about management confirmation',
    xbrlElement: 'mica:ComplianceStatementAboutManagementConfirmation',
    section: 'summary',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: '04',
    label: 'Statement about potential risks',
    xbrlElement: 'mica:StatementAboutPotentialRisks',
    section: 'summary',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: '05',
    label: 'Statement about exchangeability',
    xbrlElement: 'mica:StatementAboutExchangeabilityForOtherToken',
    section: 'summary',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: '06',
    label: 'Statement about compensation and guarantee',
    xbrlElement: 'mica:StatementAboutCompensationAndGuaranteeForOtherToken',
    section: 'summary',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: '07',
    label: 'Clarification regarding offer terms',
    xbrlElement: 'mica:ClarificationRegardingOtherTokenOfferTerms',
    section: 'summary',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: '08',
    label: 'Description of characteristics',
    xbrlElement: 'mica:DescriptionOfCharacteristicsOfOtherTokenExplanatory',
    section: 'summary',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: '09',
    label: 'Description of further information about utility tokens',
    xbrlElement: 'mica:DescriptionOfFurtherInformationAboutUtilityTokensExplanatory',
    section: 'summary',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: '10',
    label: 'Offer description',
    xbrlElement: 'mica:OfferDescriptionExplanatory',
    section: 'summary',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },

  // =====================================================================
  // PART A: Information about the Offeror
  // =====================================================================
  {
    number: 'A.1',
    label: 'Name',
    xbrlElement: 'mica:NameOfOtherTokenOfferor',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.2',
    label: 'Legal form',
    xbrlElement: 'mica:OfferorsLegalForm',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.3',
    label: 'Registered address',
    xbrlElement: 'mica:OfferorsRegisteredAddress',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.3c',
    label: 'Registered country',
    xbrlElement: 'mica:OfferorsRegisteredCountry',
    section: 'A',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'A.3s',
    label: 'Registered country subdivision',
    xbrlElement: 'mica:OfferorsRegisteredCountrySubdivision',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.4',
    label: 'Head office',
    xbrlElement: 'mica:OfferorsHeadOffice',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.4c',
    label: 'Head office country',
    xbrlElement: 'mica:OfferorsHeadOfficeCountry',
    section: 'A',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'A.5',
    label: 'Registration date',
    xbrlElement: 'mica:OfferorsRegistrationDate',
    section: 'A',
    dataType: 'dateItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.6',
    label: 'Legal entity identifier',
    xbrlElement: 'mica:OfferorsLegalEntityIdentifier',
    section: 'A',
    dataType: 'leiItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.7',
    label: 'Another identifier required pursuant to applicable national law',
    xbrlElement: 'mica:OfferorsAnotherIdentifierRequiredPursuantToApplicableNationalLaw',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.8',
    label: 'Contact telephone number',
    xbrlElement: 'mica:OfferorsContactTelephoneNumber',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.9',
    label: 'E-mail address',
    xbrlElement: 'mica:OfferorsEmailAddress',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.10',
    label: 'Response time (days)',
    xbrlElement: 'mica:OfferorsResponseTimeDays',
    section: 'A',
    dataType: 'integerItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.11',
    label: 'Parent company',
    xbrlElement: 'mica:IdentificationOfOfferorsParentCompany',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.12',
    label: 'Offeror management body member identity',
    xbrlElement: 'mica:IdentityOfOfferorsManagementBodyMemberForOtherToken',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'offerorMgmt',
  },
  {
    number: 'A.12a',
    label: 'Offeror management body member business address',
    xbrlElement: 'mica:BusinessAddressOfOfferorsManagementBodyMemberForOtherToken',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'offerorMgmt',
  },
  {
    number: 'A.12b',
    label: 'Offeror management body member function',
    xbrlElement: 'mica:FunctionOfOfferorsManagementBodyMemberForOtherToken',
    section: 'A',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'offerorMgmt',
  },
  {
    number: 'A.13',
    label: 'Business activity',
    xbrlElement: 'mica:OfferorsBusinessActivityExplanatory',
    section: 'A',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.14',
    label: 'Parent company business activity',
    xbrlElement: 'mica:ParentCompanyBusinessActivityOfOfferorSideExplanatory',
    section: 'A',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.15',
    label: 'Newly established',
    xbrlElement: 'mica:NewlyEstablishedOfferorsIndicator',
    section: 'A',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.16a',
    label: 'Financial condition for the past three years',
    xbrlElement: 'mica:InformationAboutOfferorsFinancialConditionForPastThreeYearsExplanatory',
    section: 'A',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.16b',
    label: 'Governance arrangements',
    xbrlElement: 'mica:GovernanceArrangementsExplanatory',
    section: 'A',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'A.17',
    label: 'Financial condition since registration',
    xbrlElement: 'mica:InformationAboutOfferorsFinancialConditionSinceRegistrationExplanatory',
    section: 'A',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },

  // =====================================================================
  // PART B: Information about the Issuer (if different from offeror)
  // =====================================================================
  {
    number: 'B.1',
    label: 'Issuer different from offeror or person seeking admission to trading',
    xbrlElement: 'mica:IssuerDifferentFromOfferrorOrPersonSeekingAdmissionToTrading',
    section: 'B',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.2',
    label: 'Name',
    xbrlElement: 'mica:NameOfOtherTokenIssuer',
    section: 'B',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.3',
    label: 'Legal form',
    xbrlElement: 'mica:IssuersLegalForm',
    section: 'B',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.4',
    label: 'Registered address',
    xbrlElement: 'mica:IssuersRegisteredAddress',
    section: 'B',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.4c',
    label: 'Registered country',
    xbrlElement: 'mica:IssuersRegisteredCountry',
    section: 'B',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'B.5',
    label: 'Head office',
    xbrlElement: 'mica:IssuersHeadOffice',
    section: 'B',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.5c',
    label: 'Head office country',
    xbrlElement: 'mica:IssuersHeadOfficeCountry',
    section: 'B',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'B.6',
    label: 'Registration date',
    xbrlElement: 'mica:IssuersRegistrationDate',
    section: 'B',
    dataType: 'dateItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.7',
    label: 'Legal entity identifier',
    xbrlElement: 'mica:IssuersLegalEntityIdentifier',
    section: 'B',
    dataType: 'leiItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.8',
    label: 'Another identifier required pursuant to applicable national law',
    xbrlElement: 'mica:IssuersAnotherIdentifierRequiredPursuantToApplicableNationalLaw',
    section: 'B',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.9',
    label: 'Parent company',
    xbrlElement: 'mica:IdentificationOfIssuersParentCompany',
    section: 'B',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.10',
    label: 'Issuer management body member identity',
    xbrlElement: 'mica:IdentityOfIssuersManagementBodyMemberForOtherToken',
    section: 'B',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'issuerMgmt',
  },
  {
    number: 'B.10a',
    label: 'Issuer management body member business address',
    xbrlElement: 'mica:BusinessAddressOfIssuersManagementBodyMemberForOtherToken',
    section: 'B',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'issuerMgmt',
  },
  {
    number: 'B.10b',
    label: 'Issuer management body member function',
    xbrlElement: 'mica:FunctionOfIssuersManagementBodyMemberForOtherToken',
    section: 'B',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'issuerMgmt',
  },
  {
    number: 'B.11',
    label: 'Business activity',
    xbrlElement: 'mica:IssuersBusinessActivityExplanatory',
    section: 'B',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.12',
    label: 'Parent company business activity',
    xbrlElement: 'mica:ParentCompanyBusinessActivityOfIssuerSideExplanatory',
    section: 'B',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'B.13',
    label: 'Third-party roles',
    xbrlElement: 'mica:ThirdpartyRolesExplanatory',
    section: 'B',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },

  // =====================================================================
  // PART C: Information about the Operator of the Trading Platform
  // =====================================================================
  {
    number: 'C.1',
    label: 'Name',
    xbrlElement: 'mica:NameOfOtherTokenOperator',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.2',
    label: 'Legal form',
    xbrlElement: 'mica:OperatorsLegalForm',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.3',
    label: 'Registered address',
    xbrlElement: 'mica:OperatorsRegisteredAddress',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.3c',
    label: 'Registered country',
    xbrlElement: 'mica:OperatorsRegisteredCountry',
    section: 'C',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'C.4',
    label: 'Head office',
    xbrlElement: 'mica:OperatorsHeadOffice',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.4c',
    label: 'Head office country',
    xbrlElement: 'mica:OperatorsHeadOfficeCountry',
    section: 'C',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'C.5',
    label: 'Registration date',
    xbrlElement: 'mica:OperatorsRegistrationDate',
    section: 'C',
    dataType: 'dateItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.6',
    label: 'Legal entity identifier',
    xbrlElement: 'mica:OperatorsLegalEntityIdentifier',
    section: 'C',
    dataType: 'leiItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.7',
    label: 'Another identifier required pursuant to applicable national law',
    xbrlElement: 'mica:OperatorsAnotherIdentifierRequiredPursuantToApplicableNationalLaw',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.8',
    label: 'Parent company',
    xbrlElement: 'mica:IdentificationOfOperatorsParentCompany',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.9',
    label: 'Operator management body member identity',
    xbrlElement: 'mica:IdentityOfOperatorsManagementBodyMemberForOtherToken',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'operatorMgmt',
  },
  {
    number: 'C.9a',
    label: 'Operator management body member business address',
    xbrlElement: 'mica:BusinessAddressOfOperatorsManagementBodyMemberForOtherToken',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'operatorMgmt',
  },
  {
    number: 'C.9b',
    label: 'Operator management body member function',
    xbrlElement: 'mica:FunctionOfOperatorsManagementBodyMemberForOtherToken',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'operatorMgmt',
  },
  {
    number: 'C.10',
    label: 'Number of units',
    xbrlElement: 'mica:NumberOfUnits',
    section: 'C',
    dataType: 'integerItemType',
    periodType: 'instant',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.11',
    label: 'Operator business activity',
    xbrlElement: 'mica:OperatorsBusinessActivityExplanatory',
    section: 'C',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.12a',
    label: 'Explicit consequences',
    xbrlElement: 'mica:InformationAboutOfExplicitConsequencesExplanatory',
    section: 'C',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.12b',
    label: 'Parent company business activity',
    xbrlElement: 'mica:ParentCompanyBusinessActivityOfOperatorSideExplanatory',
    section: 'C',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.13a',
    label: 'Offer phases',
    xbrlElement: 'mica:InformationAboutOfferPhasesExplanatory',
    section: 'C',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.13b',
    label: 'Other persons drawing up crypto-asset white paper',
    xbrlElement: 'mica:OtherPersonsDrawingUpCryptoassetWhitePaperExplanatory',
    section: 'C',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.14',
    label: 'Reason for drawing the white paper',
    xbrlElement: 'mica:ReasonForDrawingWhitePaperExplanatory',
    section: 'C',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.15',
    label: 'Reason for crypto-asset white paper preparation',
    xbrlElement: 'mica:ReasonForCryptoassetWhitePaperPreparationExplanatory',
    section: 'C',
    dataType: 'textBlockItemType',
    periodType: 'instant',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'C.16',
    label: 'Person involved in implementation - name',
    xbrlElement: 'mica:NameOfPersonInvolvedInImplementationOfOtherToken',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'personsInvolved',
  },
  {
    number: 'C.16a',
    label: 'Person involved in implementation - business address',
    xbrlElement: 'mica:BusinessAddressOfPersonInvolvedInImplementationOfOtherToken',
    section: 'C',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: true,
    dimensionType: 'personsInvolved',
  },
  {
    number: 'C.16b',
    label: 'Person involved in implementation - type',
    xbrlElement: 'mica:TypeOfPersonInvolvedInImplementationOfOtherToken',
    section: 'C',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: true,
    dimensionType: 'personsInvolved',
  },

  // =====================================================================
  // PART D: Information about the Crypto-Asset Project
  // =====================================================================
  {
    number: 'D.1',
    label: 'Crypto-asset project name',
    xbrlElement: 'mica:NameOfOtherTokenProject',
    section: 'D',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.2',
    label: 'Crypto-asset name',
    xbrlElement: 'mica:NameOfOtherToken',
    section: 'D',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.3',
    label: 'Abbreviation',
    xbrlElement: 'mica:OtherTokenProjectAbbreviation',
    section: 'D',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.4',
    label: 'Crypto-asset project description',
    xbrlElement: 'mica:DescriptionOfOtherTokenProjectExplanatory',
    section: 'D',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.5',
    label: 'Conditions for modifications of rights and obligations',
    xbrlElement: 'mica:InformationAboutRightsAndObligationsModificationConditionsExplanatory',
    section: 'D',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.6',
    label: 'Utility token classification',
    xbrlElement: 'mica:UtilityTokenClassificationForOtherTokenProjectIndicator',
    section: 'D',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.7',
    label: 'Key features of goods or services for utility token projects',
    xbrlElement: 'mica:KeyFeaturesOfGoodsOrServicesForUtilityTokenProjectsExplanatory',
    section: 'D',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.8',
    label: 'Planned functional use',
    xbrlElement: 'mica:PlannedFunctionalUse',
    section: 'D',
    dataType: 'dateItemType',
    periodType: 'instant',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.9',
    label: 'Token value protection schemes',
    xbrlElement: 'mica:TokenValueProtectionSchemesIndicator',
    section: 'D',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.10',
    label: 'Token value protection schemes description',
    xbrlElement: 'mica:DescriptionOfTokenValuesProtectionSchemesExplanatory',
    section: 'D',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.11',
    label: 'Compensation schemes',
    xbrlElement: 'mica:CompensationSchemesIndicator',
    section: 'D',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.12',
    label: 'Compensation schemes description',
    xbrlElement: 'mica:DescriptionOfCompensationSchemesExplanatory',
    section: 'D',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.13',
    label: 'Planned use of collected funds or other tokens',
    xbrlElement: 'mica:PlannedUseOfCollectedFundsOrOtherTokensExplanatory',
    section: 'D',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'D.14',
    label: 'Resource allocation',
    xbrlElement: 'mica:ResourceAllocationExplanatory',
    section: 'D',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },

  // =====================================================================
  // PART E: Information about the Offer to the Public / Admission to Trading
  // =====================================================================
  {
    number: 'E.1',
    label: 'Public offering or admission to trading',
    xbrlElement: 'mica:PublicOfferingOrAdmissionToTrading',
    section: 'E',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'E.2',
    label: 'Reasons for public offer or admission to trading',
    xbrlElement: 'mica:ReasonsForPublicOfferOrAdmissionToTradingExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.3',
    label: 'Maximum subscription goals (currency)',
    xbrlElement: 'mica:MaximumSubscriptionGoalsExpressedInCurrency',
    section: 'E',
    dataType: 'monetaryItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.3a',
    label: 'Maximum subscription goals (units)',
    xbrlElement: 'mica:MaximumSubscriptionGoalsExpressedInUnits',
    section: 'E',
    dataType: 'decimalItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.4',
    label: 'Minimum subscription goal (currency)',
    xbrlElement: 'mica:MinimumSubscriptionGoalExpressedInCurrency',
    section: 'E',
    dataType: 'monetaryItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.5',
    label: 'Fundraising target (currency)',
    xbrlElement: 'mica:FundraisingTargetExpressedInCurrency',
    section: 'E',
    dataType: 'monetaryItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.6',
    label: 'Oversubscription acceptance',
    xbrlElement: 'mica:OversubscriptionAcceptanceIndicator',
    section: 'E',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.7',
    label: 'Oversubscription allocation',
    xbrlElement: 'mica:OversubscriptionAllocationExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.8',
    label: 'Issue price',
    xbrlElement: 'mica:IssuePrice',
    section: 'E',
    dataType: 'decimalItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.9',
    label: 'Official currency determining issue price',
    xbrlElement: 'mica:OfficialCurrencyDeterminingIssuePrice',
    section: 'E',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'E.9a',
    label: 'Any other tokens determining issue price',
    xbrlElement: 'mica:AnyOtherOtherTokensDeterminingIssuePrice',
    section: 'E',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.10',
    label: 'Subscription fee (currency)',
    xbrlElement: 'mica:SubscriptionFeeExpressedInCurrency',
    section: 'E',
    dataType: 'monetaryItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.11',
    label: 'Offer price determination method',
    xbrlElement: 'mica:OfferPriceDeterminationMethodExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.12',
    label: 'Total number of offered or traded other tokens',
    xbrlElement: 'mica:TotalNumberOfOfferedOrTradedOtherTokens',
    section: 'E',
    dataType: 'integerItemType',
    periodType: 'instant',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.13',
    label: 'Targeted holders',
    xbrlElement: 'mica:TargetedHoldersForOtherToken',
    section: 'E',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'E.14',
    label: 'Holder restrictions',
    xbrlElement: 'mica:HolderRestrictionsExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.15',
    label: 'Reimbursement notice',
    xbrlElement: 'mica:ReimbursementNotice',
    section: 'E',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.16',
    label: 'Refund mechanism',
    xbrlElement: 'mica:RefundMechanismExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.17',
    label: 'Refund timeline',
    xbrlElement: 'mica:RefundTimelineExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.18',
    label: 'Offer phases',
    xbrlElement: 'mica:DescriptionOfOtherTokenProjectPhasesExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.19',
    label: 'Early purchase discount',
    xbrlElement: 'mica:DisclosureOfEarlyPurchaseDiscountExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.20',
    label: 'Time-limited offer',
    xbrlElement: 'mica:TimelimitedOfferIndicator',
    section: 'E',
    dataType: 'booleanItemType',
    periodType: 'instant',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.21',
    label: 'Subscription period beginning',
    xbrlElement: 'mica:SubscriptionPeriodBeginning',
    section: 'E',
    dataType: 'dateItemType',
    periodType: 'instant',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.22',
    label: 'Subscription period end',
    xbrlElement: 'mica:SubscriptionPeriodEnd',
    section: 'E',
    dataType: 'dateItemType',
    periodType: 'instant',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.23',
    label: 'Safeguarding arrangements for offered funds or other tokens',
    xbrlElement: 'mica:SafeguardingArrangementsForOfferedFundsOrOtherTokensExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.24',
    label: 'Payment methods for other token purchase',
    xbrlElement: 'mica:PaymentMethodsForOtherTokenPurchaseExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.25',
    label: 'Value transfer methods for reimbursement',
    xbrlElement: 'mica:ValueTransferMethodsForReimbursementExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.26',
    label: 'Right of withdrawal',
    xbrlElement: 'mica:RighOfWithdrawalExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.27',
    label: 'Transfer of purchased other tokens',
    xbrlElement: 'mica:TransferOfPurchasedOtherTokensExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.28',
    label: 'Transfer time schedule',
    xbrlElement: 'mica:TransferTimeSchedule',
    section: 'E',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.29',
    label: "Purchaser's technical requirements",
    xbrlElement: 'mica:PurchasersTechnicalRequirementsExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.30',
    label: 'Other token service provider (CASP) name',
    xbrlElement: 'mica:NameOfOtherTokenServiceProvider',
    section: 'E',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.31',
    label: 'CASP identifier',
    xbrlElement: 'mica:OtherTokenServiceProviderIdentifier',
    section: 'E',
    dataType: 'leiItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.32',
    label: 'Placement form',
    xbrlElement: 'mica:PlacementFormForOtherToken',
    section: 'E',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'E.33',
    label: 'Trading platforms name',
    xbrlElement: 'mica:TradingPlatformsName',
    section: 'E',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.34',
    label: 'Trading platforms market identifier code (MIC)',
    xbrlElement: 'mica:TradingPlatformsIdentifierCode',
    section: 'E',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.35',
    label: 'Trading platforms access',
    xbrlElement: 'mica:TradingPlatformsAccessExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.36',
    label: 'Involved costs',
    xbrlElement: 'mica:DescriptionOfInvolvedCostsExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.37',
    label: 'Offer expenses',
    xbrlElement: 'mica:DescriptionOfOfferExpensesExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.38',
    label: 'Conflicts of interest',
    xbrlElement: 'mica:InformationAboutPotentialConflictsOfInterestForOtherTokenExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.39',
    label: 'Applicable law',
    xbrlElement: 'mica:ApplicableLawForOtherTokenOfferExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'E.40',
    label: 'Competent court',
    xbrlElement: 'mica:CompetentCourtForOtherTokenOfferExplanatory',
    section: 'E',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },

  // =====================================================================
  // PART F: Information about the Crypto-Asset
  // =====================================================================
  {
    number: 'F.1',
    label: 'Other token type',
    xbrlElement: 'mica:OtherTokenType',
    section: 'F',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.2',
    label: 'Other token functionality',
    xbrlElement: 'mica:InformationAboutOtherTokenFunctionalityExplanatory',
    section: 'F',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.3',
    label: 'Planned application of functionalities',
    xbrlElement: 'mica:InformationAboutPlannedApplicationOfFunctionalitiesExplanatory',
    section: 'F',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.4',
    label: 'Type of crypto-asset white paper',
    xbrlElement: 'mica:OtherTokenTypeOfWhitePaper',
    section: 'F',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'F.5',
    label: 'Type of submission',
    xbrlElement: 'mica:OtherTokenTypeOfSubmission',
    section: 'F',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'F.6',
    label: 'Other token characteristics',
    xbrlElement: 'mica:DescriptionOfOtherTokenCharacteristicsExplanatory',
    section: 'F',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.7',
    label: 'Commercial name or trading name',
    xbrlElement: 'mica:OtherTokenIssuersCommercialOrTradingName',
    section: 'F',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.8',
    label: 'Website of the issuer',
    xbrlElement: 'mica:OtherTokenIssuersWebsite',
    section: 'F',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.9',
    label: 'Starting date of offer to the public or admission to trading',
    xbrlElement: 'mica:OtherTokenOfferStartingDate',
    section: 'F',
    dataType: 'dateItemType',
    periodType: 'instant',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.10',
    label: 'Publication date',
    xbrlElement: 'mica:OtherTokenWhitePaperPublicationDate',
    section: 'F',
    dataType: 'dateItemType',
    periodType: 'instant',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.11',
    label: 'Any other services provided by the issuer',
    xbrlElement: 'mica:InformationAboutOtherServicesProvidedByOtherTokenIssuerExplanatory',
    section: 'F',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.12',
    label: 'Language or languages of white paper',
    xbrlElement: 'mica:InformationAboutLanguagesUsedInOtherTokenWhitePaper',
    section: 'F',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.13',
    label: 'Digital token identifier code',
    xbrlElement: 'mica:OtherTokenDigitalTokenIdentifierCode',
    section: 'F',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.14',
    label: 'Functionally fungible group digital token identifier',
    xbrlElement: 'mica:OtherTokenFunctionallyFungibleGroupDigitalTokenIdentifier',
    section: 'F',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.15',
    label: 'Voluntary data flag',
    xbrlElement: 'mica:OtherTokenVoluntaryDataFlagIndicator',
    section: 'F',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.16',
    label: 'Personal data flag',
    xbrlElement: 'mica:OtherTokenPersonalDataFlagIndicator',
    section: 'F',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.17',
    label: 'LEI eligibility',
    xbrlElement: 'mica:LEIEligibilityIndicatorForOtherToken',
    section: 'F',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'F.18',
    label: 'Home member state',
    xbrlElement: 'mica:OtherTokenHomeMemberState',
    section: 'F',
    dataType: 'enumerationItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },
  {
    number: 'F.19',
    label: 'Host member states',
    xbrlElement: 'mica:OtherTokenHostMemberStates',
    section: 'F',
    dataType: 'enumerationSetItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: true,
    isDimensional: false,
  },

  // =====================================================================
  // PART G: Rights and Obligations
  // =====================================================================
  {
    number: 'G.1',
    label: 'Purchaser rights and obligations',
    xbrlElement: 'mica:InformationAboutPurchaserRightsAndObligationsExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.2',
    label: 'Exercise of rights and obligations',
    xbrlElement: 'mica:ExerciseOfRightsAndObligationExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.3',
    label: 'Conditions for modifications of rights and obligations',
    xbrlElement: 'mica:InformationAboutConditionsForModificationsOfRightsAndObligationsExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.4',
    label: 'Future public offers',
    xbrlElement: 'mica:InformationAboutFuturePublicOffersExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.5',
    label: 'Issuer retained other token',
    xbrlElement: 'mica:NumberOfIssuersRetainedOtherTokens',
    section: 'G',
    dataType: 'integerItemType',
    periodType: 'instant',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.6',
    label: 'Utility token classification',
    xbrlElement: 'mica:UtilityTokenClassificationForOtherTokenIndicator',
    section: 'G',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.7',
    label: 'Key features of goods or services utility tokens',
    xbrlElement: 'mica:KeyFeaturesOfGoodsAndServicesOfUtilityTokensExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.8',
    label: 'Utility tokens redemption',
    xbrlElement: 'mica:UtilityTokensRedemptionExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.9',
    label: 'Non-trading request',
    xbrlElement: 'mica:NontradingRequestIndicatorRelatedToOtherTokens',
    section: 'G',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.10',
    label: 'Other tokens purchase or sale modalities',
    xbrlElement: 'mica:OtherTokensPurchaseOrSaleModalitiesExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.11',
    label: 'Other tokens transfer restrictions',
    xbrlElement: 'mica:OtherTokensTransferRestrictionsExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.12',
    label: 'Supply adjustment protocols',
    xbrlElement: 'mica:SupplyAdjustmentProtocolsIndicator',
    section: 'G',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.13',
    label: 'Supply adjustment mechanisms',
    xbrlElement: 'mica:SupplyAdjustmentMechanismsExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.14',
    label: 'Token value protection schemes',
    xbrlElement: 'mica:OtherTokenValueProtectionSchemesIndicator',
    section: 'G',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.15',
    label: 'Token value protection schemes description',
    xbrlElement: 'mica:DescriptionOfOtherTokenValueProtectionSchemesExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.16',
    label: 'Compensation schemes',
    xbrlElement: 'mica:OtherTokenCompensationSchemesIndicator',
    section: 'G',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.17',
    label: 'Compensation schemes description',
    xbrlElement: 'mica:DescriptionOfOtherTokenCompensationSchemesExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.18',
    label: 'Applicable law',
    xbrlElement: 'mica:ApplicableLawForOtherTokenExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'G.19',
    label: 'Competent court',
    xbrlElement: 'mica:CompetentCourtForOtherTokenExplanatory',
    section: 'G',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },

  // =====================================================================
  // PART H: Information on the Underlying Technology
  // =====================================================================
  {
    number: 'H.1',
    label: 'Distributed ledger technology (DLT)',
    xbrlElement: 'mica:DistributedLedgerTechnologyForOtherTokenExplanatory',
    section: 'H',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'H.2',
    label: 'Protocols and technical standards',
    xbrlElement: 'mica:ProtocolsAndTechnicalStandardsForOtherTokenExplanatory',
    section: 'H',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'H.3',
    label: 'Technology used',
    xbrlElement: 'mica:InformationAboutTechnologyUsedForOtherTokenExplanatory',
    section: 'H',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'H.4',
    label: 'Consensus mechanism',
    xbrlElement: 'mica:ConsensusMechanismForOtherTokenExplanatory',
    section: 'H',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'H.5',
    label: 'Incentive mechanisms and applicable fees',
    xbrlElement: 'mica:IncentiveMechanismsAndApplicableFeesForOtherTokenExplanatory',
    section: 'H',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'H.6',
    label: 'Use of distributed ledger technology',
    xbrlElement: 'mica:UseOfDistributedLedgerTechnologyIndicatorForOtherToken',
    section: 'H',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'H.7',
    label: 'DLT functionality description',
    xbrlElement: 'mica:DescriptionOfDLTFunctionalityForOtherTokenExplanatory',
    section: 'H',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'H.8',
    label: 'Audit',
    xbrlElement: 'mica:AuditIndicatorForOtherToken',
    section: 'H',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'H.9',
    label: 'Audit outcome',
    xbrlElement: 'mica:AuditOutcomeForOtherTokenExplanatory',
    section: 'H',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },

  // =====================================================================
  // PART I: Risk Disclosure / Compliance Statements
  // =====================================================================
  {
    number: 'I.00',
    label: 'Table of content',
    xbrlElement: 'mica:TableOfContentForAssetReferencedTokenWhitePaper',
    section: 'I',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'I.1',
    label: 'Offer-related risks',
    xbrlElement: 'mica:DescriptionOfOfferrelatedRisksForOtherTokenExplanatory',
    section: 'I',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'I.2',
    label: 'Issuer-related risks',
    xbrlElement: 'mica:DescriptionOfIssuerrelatedRisksForOtherTokenExplanatory',
    section: 'I',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'I.02a',
    label: 'Statement on issuer responsibility for white paper content',
    xbrlElement: 'mica:StatementOnIssuerResponsibilityForWhitePaperContent',
    section: 'I',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'I.02b',
    label: 'Statement on value and transferability risks',
    xbrlElement: 'mica:StatementOnValueAndTransferabilityRisks',
    section: 'I',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'I.03',
    label: 'Compliance statement on information accuracy',
    xbrlElement: 'mica:ComplianceStatementOnInformationAccuracy',
    section: 'I',
    dataType: 'booleanItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'I.3',
    label: 'Other tokens-related risks',
    xbrlElement: 'mica:OtherTokensrelatedRisksExplanatory',
    section: 'I',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'I.4',
    label: 'Project implementation-related risks',
    xbrlElement: 'mica:ProjectImplementationrelatedRisksExplanatory',
    section: 'I',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'I.5',
    label: 'Technology-related risks',
    xbrlElement: 'mica:DescriptionOfTechnologyrelatedRisksForOtherTokenExplanatory',
    section: 'I',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'I.6',
    label: 'Mitigation measures',
    xbrlElement: 'mica:MitigationMeasuresForTechnologyRiskForOtherTokenExplanatory',
    section: 'I',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'I.07',
    label: 'Key information about the offer to the public and or admission to trading',
    xbrlElement: 'mica:KeyInformationAboutOfferToPublicAndOrAdmissionToTradingExplanatory',
    section: 'I',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },

  // =====================================================================
  // PART J: Information on Sustainability
  // =====================================================================
  {
    number: 'J.1',
    label: 'Adverse impacts on climate and other environment-related adverse impacts',
    xbrlElement: 'mica:InformationOnAdverseImpactsOnClimateAndOtherEnvironmentrelatedAdverseImpactsForOtherTokenTokenExplanatory',
    section: 'J',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },

  // =====================================================================
  // SUSTAINABILITY INDICATORS (S.x) - Annex III
  // =====================================================================
  {
    number: 'S.1',
    label: 'Name',
    xbrlElement: 'mica:Name',
    section: 'S',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.2',
    label: 'Relevant legal entity identifier',
    xbrlElement: 'mica:RelevantLegalEntityIdentifier',
    section: 'S',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.3',
    label: 'Name of crypto-asset',
    xbrlElement: 'mica:NameOfCryptoAssetSustainability',
    section: 'S',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.4',
    label: 'Consensus mechanism',
    xbrlElement: 'mica:ConsensusMechanismSustainabilityExplanatory',
    section: 'S',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.5',
    label: 'Incentive mechanisms and applicable fees',
    xbrlElement: 'mica:IncentiveMechanismsAndApplicableFeesSustainabilityExplanatory',
    section: 'S',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.6',
    label: 'Beginning of period',
    xbrlElement: 'mica:BeginningOfPeriodToWhichDisclosedInformationRelates',
    section: 'S',
    dataType: 'dateItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.7',
    label: 'End of period',
    xbrlElement: 'mica:EndOfPeriodToWhichDisclosedInformationRelates',
    section: 'S',
    dataType: 'dateItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.8',
    label: 'Energy consumption',
    xbrlElement: 'mica:EnergyConsumption',
    section: 'S',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.9',
    label: 'Description of energy consumption sources and methodologies',
    xbrlElement: 'mica:DescriptionOfEnergyConsumptionSourcesAndMethodologiesExplanatory',
    section: 'S',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.10',
    label: 'Renewable energy consumption percentage',
    xbrlElement: 'mica:RenewableEnergyConsumptionPercentage',
    section: 'S',
    dataType: 'percentItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.11',
    label: 'Energy intensity',
    xbrlElement: 'mica:EnergyIntensity',
    section: 'S',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.12',
    label: 'Scope 1 DLT GHG emissions (controlled)',
    xbrlElement: 'mica:Scope1DLTGHGEmissionsControlled',
    section: 'S',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.13',
    label: 'Scope 2 DLT GHG emissions (purchased)',
    xbrlElement: 'mica:Scope2DLTGHGEmissionsPurchased',
    section: 'S',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.14',
    label: 'GHG intensity',
    xbrlElement: 'mica:GHGIntensity',
    section: 'S',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.15',
    label: 'Key energy sources and methodologies',
    xbrlElement: 'mica:DescriptionOfKeyEnergySourcesAndMethodologiesExplanatory',
    section: 'S',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.16',
    label: 'Key GHG sources and methodologies',
    xbrlElement: 'mica:DescriptionOfKeyGHGSourcesAndMethodologiesExplanatory',
    section: 'S',
    dataType: 'textBlockItemType',
    periodType: 'duration',
    isTextBlock: true,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.17',
    label: 'Energy mix',
    xbrlElement: 'mica:EnergyMixPercentage',
    section: 'S',
    dataType: 'percentItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.18',
    label: 'Energy use reduction',
    xbrlElement: 'mica:EnergyUseReductionDetailsAbstract',
    section: 'S',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.19',
    label: 'Carbon intensity',
    xbrlElement: 'mica:CarbonIntensity',
    section: 'S',
    dataType: 'decimalItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
  {
    number: 'S.20',
    label: 'Scope 3 DLT GHG emissions (value chain)',
    xbrlElement: 'mica:Scope3DLTGHGEmissionsValueChain',
    section: 'S',
    dataType: 'stringItemType',
    periodType: 'duration',
    isTextBlock: false,
    isHidden: false,
    isDimensional: false,
  },
];

/**
 * Section titles for MiCA Parts
 */
export const SECTION_TITLES: Record<string, string> = {
  summary: 'Summary',
  A: 'Part A: Information about the Offeror',
  B: 'Part B: Information about the Issuer',
  C: 'Part C: Information about the Operator of the Trading Platform',
  D: 'Part D: Information about the Crypto-Asset Project',
  E: 'Part E: Information about the Offer to the Public or Admission to Trading',
  F: 'Part F: Information about the Crypto-Asset',
  G: 'Part G: Rights and Obligations',
  H: 'Part H: Information on the Underlying Technology',
  I: 'Part I: Risk Disclosure and Compliance Statements',
  J: 'Part J: Information on Sustainability',
  S: 'Annex III: Sustainability Indicators',
};

/**
 * Get fields for a specific section
 */
export function getFieldsForSection(section: WhitepaperPart | 'summary' | 'S'): MiCAFieldDefinition[] {
  return OTHR_FIELD_DEFINITIONS.filter(f => f.section === section);
}

/**
 * Get a field by its XBRL element name
 */
export function getFieldByElement(xbrlElement: string): MiCAFieldDefinition | undefined {
  return OTHR_FIELD_DEFINITIONS.find(f => f.xbrlElement === xbrlElement);
}

/**
 * Get all non-dimensional fields (for standard table rendering)
 */
export function getStandardFields(): MiCAFieldDefinition[] {
  return OTHR_FIELD_DEFINITIONS.filter(f => !f.isDimensional);
}

/**
 * Get all dimensional fields for a specific dimension type
 */
export function getDimensionalFields(dimensionType: MiCAFieldDefinition['dimensionType']): MiCAFieldDefinition[] {
  return OTHR_FIELD_DEFINITIONS.filter(f => f.dimensionType === dimensionType);
}
