/**
 * Page Layout
 *
 * Generates the cover page, table of contents, and A4 page wrappers
 * for the MiCA whitepaper iXBRL document.
 */

import { escapeHtml } from './inline-tagger';
import { SECTION_TITLES } from '../mica-template/field-definitions';
import type { WhitepaperPart } from '@/types/taxonomy';

/**
 * Document metadata for the cover page
 */
export interface CoverPageData {
  /** Crypto-asset project name */
  projectName: string;
  /** Crypto-asset name */
  cryptoAssetName: string;
  /** Ticker symbol */
  symbol: string;
  /** Offeror legal name */
  offerorName: string;
  /** Document date */
  documentDate: string;
  /** Language */
  language: string;
  /** Optional base64-encoded logo image */
  logoBase64?: string;
  /** Logo MIME type (e.g., "image/png") */
  logoMimeType?: string;
}

/**
 * Generate the cover page HTML.
 */
export function renderCoverPage(data: CoverPageData): string {
  const logoHtml = data.logoBase64 && data.logoMimeType
    ? `<img class="logo" src="data:${data.logoMimeType};base64,${data.logoBase64}" alt="Logo" />`
    : '';

  return `
  <div class="page cover-page">
    ${logoHtml}
    <div class="title">Crypto-Asset White Paper</div>
    <div class="subtitle">${escapeHtml(data.cryptoAssetName)} (${escapeHtml(data.symbol)})</div>
    <div class="meta">
      <p>${escapeHtml(data.offerorName)}</p>
      <p>Pursuant to Regulation (EU) 2023/1114 (MiCA)</p>
      <p>Date: ${escapeHtml(data.documentDate)}</p>
    </div>
  </div>`;
}

/**
 * Generate the table of contents page.
 */
export function renderTableOfContents(
  activeSections: (WhitepaperPart | 'summary' | 'S')[]
): string {
  const tocEntries = activeSections
    .map(section => {
      const title = SECTION_TITLES[section] || section;
      const anchor = `section-${section}`;
      return `      <li><span class="toc-number">${section === 'summary' ? '' : section === 'S' ? 'Annex III' : `Part ${section}`}</span><a href="#${anchor}">${escapeHtml(title)}</a></li>`;
    })
    .join('\n');

  return `
  <div class="page">
    <div class="toc">
      <h2>Table of Contents</h2>
      <ul>
${tocEntries}
      </ul>
    </div>
  </div>`;
}

/**
 * Wrap section content in an A4 page div.
 */
export function wrapInPage(content: string, pageId?: string): string {
  const idAttr = pageId ? ` id="${pageId}"` : '';
  return `
  <div class="page"${idAttr}>
${content}
  </div>`;
}

/**
 * Generate a page footer.
 */
export function renderPageFooter(pageNumber?: number): string {
  const pageText = pageNumber !== undefined ? `Page ${pageNumber}` : '';
  return `
    <div class="page-footer">
      ${pageText} | MiCA Crypto-Asset White Paper | Generated by WhitePaperXBRL
    </div>`;
}
